apiVersion: v1
kind: Secret
metadata:
  name: aks-secret
type: Opaque
data:
  UC_AKSTENANT: {{ .Values.aks.tenant | b64enc }}
  UC_AKSCLIENT: {{ .Values.aks.client | b64enc }}
  UC_AKSSECRET: {{ .Values.aks.secret | b64enc }}
  UC_AKSSUBSCRIPTION: {{ .Values.aks.subscription | b64enc }}
  UC_AKSREGION: {{ .Values.aks.region | b64enc }}
  UC_AKSSTORAGEKEY: {{ .Values.aks.storagekey | b64enc }}
  UC_ALLOCATEDOUTBOUNDIPS: {{ .Values.aks.outboundip | b64enc }}