apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "uc-rancher.fullname" . }}
  labels:
    {{- include "uc-rancher.labels" . | nindent 4 }}
spec:
  template:
    spec:
      volumes:
      - name: init-script-volume
        configMap:
          name: init-script-configmap
          defaultMode: 0700
      imagePullSecrets:
        - name: ucregistry
      containers:
        - name: uc
          volumeMounts:
          - name: init-script-volume
            mountPath: /init.sh
            subPath: init.sh
          image: "{{ .Values.ucimage }}"
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args: ["uc --backend AKS create {{ .Values.jobid }} --wait || true"]
          envFrom:
          - secretRef:
              name: aks-secret
          - secretRef:
              name: registry-secret
          - configMapRef:
              name: jobconfig-env
      restartPolicy: Never
  backoffLimit: 0
