apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uc-pv-claim
spec:
  storageClassName: {{ .Values.storageclass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
