# © 2021, TheUberCloud, Inc. All rights reserved
apiVersion: v1
kind: Secret
metadata:
  name: service-account-secret
  labels:
    app: {{ template "uc-ui.name" . }}
    chart: {{ template "uc-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  service-account.json: {{ .Values.uc.credentials | trim }}
# © 2021, TheUberCloud, Inc. All rights reserved