# © 2021, TheUberCloud, Inc. All rights reserved
apiVersion: v1
kind: Secret
metadata:
  name: ubercloud-registry-secret
  labels:
    app: {{ template "uc-ui.name" . }}
    chart: {{ template "uc-ui.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  .dockerconfigjson: {{ .Values.uc.credentials | trim }}
type: kubernetes.io/dockerconfigjson
# © 2021, TheUberCloud, Inc. All rights reserved