apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
type: Opaque
data:
  UC_REGISTRY: "{{ .Values.registry.address | b64enc }}"
  UC_USERNAME: "{{ .Values.registry.username | b64enc }}"
  UC_PASSWORD: "{{ .Values.registry.password | b64enc }}"
  UC_EMAIL: "ZHVtbXlAcmVnaXN0cnkuaW8="
